exclude:
  - message: yaml-cpp Third Party Directory
    paths:
      - third-party/yaml-cpp
  - message: False Positives, UMAA Includes
    pattern: "UMAA/*[a-zA-Z3\/]*"
  - message: Commit hash in permalink to reference implementation
    paths:
      - include/algorithms/GeographicUtils.h
    pattern: "[A-Za-z0-9]*"

