#---------------------------------------------------------------------------
# Applied Research Laboratory
# Pennsylvania State University
# P.O. Box 30
# State College, PA 16804-0030
#
# Copyright 2022 The Pennsylvania State University
#---------------------------------------------------------------------------
#
# Analysis parameters for SonarQube: https://docs.sonarqube.org/latest/analysis/analysis-parameters/
# Must be unique in a given SonarQube instance "my:project" is not a valid value.
sonar.projectKey=umaa-sdk-common

# --- optional properties ---

# defaults to project key
sonar.projectName=umaa-sdk-common
# defaults to 'not provided'
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Defaults to .
# Multiple pathes may be included if comma seperated.
sonar.sources=src,include

# Test directories may be specified to be ignored. Path is relative to the sonar-project.properties file. Defaults to .
sonar.tests=test

# Define a pattern that matches the expected test directoreis and add the underlying files to the test group. If there needs to be specifics outside of just sonar.tests
# sonar.test.inclusion=

# Files that should be excluded from coverage. Path is relative to the sonar-project.properties file. Defaults to .
sonar.coverage.exclusions=test/**/*,third_party/**/*

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Enable support for C++23
sonar.cfamily.cpp23.enabled=true
