//---------------------------------------------------------------------------
// Copyright 2025 Pennsylvania State University
//
// Applied Research Laboratory
// Pennsylvania State University
// P.O. Box 30
// State College, PA 16804-0030
//
// DISTRIBUTION STATEMENT A. Approved for public release.
// Distribution is unlimited.
// This software was developed by the Department of the Navy,
// NAVSEA Unmanned and Small Combatants. It is provided under the terms of
// use found in the LICENSE file at the source code root directory.
//
//---------------------------------------------------------------------------

#ifndef INCLUDE_UMAA_OBJECTIVE_EXECUTORS_SERVICES_GLOBALWAYPOINTCONTROLSERVICECONSUMER_H_
#define INCLUDE_UMAA_OBJECTIVE_EXECUTORS_SERVICES_GLOBALWAYPOINTCONTROLSERVICECONSUMER_H_

#include <memory>
#include <vector>

#include "CommandConsumerBase.h"
#include "LargeListWriter.h"
#include "GlobalWaypointControlServiceConsumerIo.h"

namespace arlcore::umaa {

//! \brief Waypoint Control Service Consumer concrete command consumer implementation
class GlobalWaypointControlServiceConsumer :
  public arlcore::umaa::services::CommandConsumerBase<
    GlobalWaypointCommandType,
    GlobalWaypointCommandAckReportType,
    GlobalWaypointCommandStatusType,
    GlobalWaypointExecutionStatusReportType>,
  public arlcore::umaa::LargeListWriter<
    GlobalWaypointType,
    GlobalWaypointCommandTypeWaypointsListElement> {
 public:
  //! \brief Delete default constructor
  GlobalWaypointControlServiceConsumer() = delete;

  //! \brief Constructor
  //! \param cmdHdr A UMAA Command Header object that should have a unique source and destination id
  //! Session ID does not need to be set since it is generated by this class
  //! \param io constant Io object that holds shared pointers to base readers and writers
  //! \param largeListIo constant shared pointer to a base sender object
  GlobalWaypointControlServiceConsumer(
    const CommandHeader& cmdHdr,
    std::shared_ptr<GlobalWaypointControlServiceConsumerIo> io);

  //! \brief Constructor with initial waypoints list
  //! \param cmdHdr  A UMAA Command Header object that should have a unique source and destination id
  //! Session ID does not need to be set since it is generated by this class
  //! \param io constant Io object that holds shared pointers to base readers and writers
  //! \param largeListIo largeListIo constant shared pointer to a base sender object
  //! \param waypoints A reference to a vector of waypoint types to add and publish to an initial large list
  GlobalWaypointControlServiceConsumer(
    const CommandHeader& cmdHdr,
    std::shared_ptr<GlobalWaypointControlServiceConsumerIo> io,
    const std::vector<GlobalWaypointType>& waypoints);

  ~GlobalWaypointControlServiceConsumer() override;

  //! \brief Overridden send function to send a command in coordination with a large list
  //! \param cmd The waypoint command to send
  //! \return SendStatus enum
  SendStatus send(GlobalWaypointCommandType* cmd) override;

  //! \brief Implementation specific teardown logic to clean up waypoint large list
  //! \return SendStatus enum
  SendStatus sessionTearDown() override;
};

}  // namespace arlcore::umaa
#endif  // INCLUDE_UMAA_OBJECTIVE_EXECUTORS_SERVICES_GLOBALWAYPOINTCONTROLSERVICECONSUMER_H_
